#!/usr/bin/perl

##########################################################################
# $Id: sysstat-selfnet,v 0.1 2013/04/23 04:32:00 Andreas Boesen Exp $
##########################################################################
# $Log: sysstat-selfnet,v $
# Revision 0.1  2013/04/23 08:00:00  andreasb -at- selnfet.de
# Initial Version
##########################################################################

# This script prints out information about the CPU utilization for the
# system, the CPU utilization for the currently working Linux tasks and
# the memory utilization - all for the working Linux tasks at the moment 
# the report is generated.
# To do this the 'iostat' and the 'pidstat' utilities from the 'sysstat' 
# package are being used. 
#  http://packages.debian.org/search?keywords=sysstat
#  http://sebastien.godard.pagesperso-orange.fr/

##########################################################################
## Copyright 2013 - Andreas Boesen / Selfnet e.V. (http://www.selfnet.de)
##
## You can choose one of the following licences for this script:
## * LGPL v2.1
## * "THE BEER-WARE LICENSE" (Revision 42)
## * WTFPL
## * MIT/X-Consortium License
##
## Of course donations to the Selfnet e.V. (a non-profit organisation in
## Stuttgart/Germany) are always welcome. :-)
##
## ==== LGPL v2.1 ====
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the GNU Lesser General Public License
## (LGPL) version 2.1 which accompanies this distribution, and is available at
## http://www.gnu.org/licenses/lgpl-2.1.html
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
## Lesser General Public License for more details.
##
## ==== THE BEER-WARE LICENSE ====
## "THE BEER-WARE LICENSE" (Revision 42):
## <andreasb -at- selfnet.de> wrote this file. As long as you retain this
## notice you can do whatever you want with this stuff. If we meet some day,
## and you think this stuff is worth it, you can buy me a beer in return.
## Andreas Boesen
##
## ==== WTFPL ====
## Copyright © 2013 Andreas Boesen <andreasb -at- selfnet.de>
## This work is free. You can redistribute it and/or modify it under the
## terms of the Do What The Fuck You Want To Public License, Version 2,
## as published by Sam Hocevar. See http://www.wtfpl.net/ for more details.
##
## ==== MIT/X-Consortium License ====
## ## Copyright (c) 2008 Laurent Dufour
## Covered under the included MIT/X-Consortium License:
##    http://www.opensource.org/licenses/mit-license.php
## All modifications and contributions by other persons to this script are assumed
## to have been donated to the Logwatch project and thus assume the above copyright
## and licensing terms. If you want to make contributions under your own copyright
## or a different license this must be explicitly stated in the contribution an the
## Logwatch project reserves the right to not accept such contributions. If you have
## made significant contributions to this script and want to claim copyright please
## contact logwatch-devel@lists.sourceforge.net.
##
##
## Attribution: kirk from the zz-sys file (v 1.3) file I used as a template
##              because I never touched a Perl script before in my life. :-)
##########################################################################




eval "require File::Which";
if($@) {
   print STDERR "No File::CPU module installed. To istall, execute the command:\n";
   print STDERR "   perl -MCPAN -e 'install File::Which' \n\n";
} else {
   use File::Which;
   my $iostatPath = which('iostat');
   my $pidstatPath = which('pidstat');

#  Check if iostat is working.
   if ($iostatPath eq ""){
      print STDERR "Please install the iostat tool. It is usually provided by the ";
      print STDERR "'sysstat' package on Debian GNU/Linux systems. \n";
      print STDERR "http://packages.debian.org/search?keywords=sysstat&searchon=names&section=all\n";
      print STDERR "On Debian and Debian based systems you should be able to install it by executing ";
      print STDERR "the following command as root or by prefixing the sudo command:\n";
      print STDERR "   aptitude install sysstat \n\n";
   } else {
#     Correct Indention :-) (+3 whitespaces after each \n) (s/\n/\n   /g)
      my $iostatText = `$iostatPath -c`;
      $iostatText =~ s/^/  /g;
      $iostatText =~ s/\n/\n   /g;

#     Print out iostat report - only cpu stats
      print " IOstat Report - CPU statistics\n";
      print $iostatText;
      print "\n\n";
   }

#  Check if pidstat is working.
   if ($pidstatPath eq ""){
      print STDERR "Please install the pidstat tool. It is usually provided by the ";
      print STDERR "'sysstat' package on Debian GNU/Linux systems. \n";
      print STDERR "http://packages.debian.org/search?keywords=sysstat&searchon=names&section=all\n";
      print STDERR "On Debian and Debian based systems you should be able to install it by executing ";
      print STDERR "the following command as root or by prefixing the sudo command:\n";
      print STDERR "   aptitude install sysstat \n\n";
   } else {
#     Correct Indention :-) (+3 whitespaces after each \n) (s/\n/\n   /g)
      my $pidstatCpuText = `$pidstatPath -u`;
      $pidstatCpuText =~ s/^/  /g;
      $pidstatCpuText =~ s/\n/\n   /g;
#     Print out pidstat report for cpu.
      print " PIDstat Report - Report CPU utilization.\n";
      print $pidstatCpuText;
      print "\n\n";

#     Correct Indention :-) (+3 whitespaces after each \n) (s/\n/\n   /g)
      my $pidstatMemText = `$pidstatPath -r`;
      $pidstatMemText =~ s/^/  /g;
      $pidstatMemText =~ s/\n/\n   /g;
#     Print out pidstat report for memory usage.
      print " PIDstat Report - Report page faults and memory utilisation.\n";
      print $pidstatMemText;
      print "\n\n";
   }

}

exit(0);

# vi: shiftwidth=3 tabstop=3 syntax=perl et
# Local Variables:
# mode: perl
# perl-indent-level: 3
# indent-tabs-mode: nil
# End:

