#!/bin/bash

# This file is a bash script called "check_mysql_nscd_user".
# Copyright (C) 2014 Andreas Boesen
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

## Author:      Andreas Boesen
## E-Mail:      andreasb -at- NOSPAM DOT selfnet dot de
## Usage:       command[check_mysql_nscd_user]=/usr/lib/nagios/plugins/check_mysql_nscd_user
## Abstract:    Checks if a user is available using `id`. In my case I set a user that is
##		only available through libnss in a MySQL database.
## Date:        2014-03-11
## Version:     0.1
## Licence:     GPLv2

#config
USER=adalovelace
USERID=10000
GROUP=adalovelace
GROUPID=10000
#/config

GETENT=`/usr/bin/id $USER`
CORRECT="uid=$USERID($USER) gid=$GROUPID($GROUP) Gruppen=$GROUPID($GROUP)"

case "$GETENT" in
$CORRECT)  echo "OK - libnss (system login with mysql) seems to be working"
   exit 0
   ;;
*) echo "CRITICAL - libnss (system login with mysql) is not working"
   exit 2
   ;;
esac
